# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.5.2-tower) on: Tue 28. Jul 12:32:55 2009
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile_0xE55B478A.mk
#  Part of     : QDetroBro
#  Description : This file is used to call necessary targets on wrapper makefile
#                during normal Symbian build process.
#  Version     : 
#
# ==============================================================================



MAKE = make

do_nothing :
	@rem do_nothing

MAKMAKE: create_temps pre_targetdeps

LIB: create_temps pre_targetdeps

BLD: create_temps pre_targetdeps

ifeq "$(PLATFORM)" "WINSCW"
CLEAN: extension_clean winscw_deployment_clean
else
CLEAN: extension_clean
endif

CLEANLIB: do_nothing

RESOURCE: do_nothing

FREEZE: do_nothing

SAVESPACE: do_nothing

RELEASABLES: do_nothing

ifeq "$(PLATFORM)" "WINSCW"
FINAL: finalize winscw_deployment
else
FINAL: finalize
endif

pre_targetdeps : c:\Symbian\Carbide\workspace\QDetroBro\Makefile
	-$(MAKE) -f "c:\Symbian\Carbide\workspace\QDetroBro\Makefile" pre_targetdeps

create_temps : c:\Symbian\Carbide\workspace\QDetroBro\Makefile
	-$(MAKE) -f "c:\Symbian\Carbide\workspace\QDetroBro\Makefile" create_temps

extension_clean : c:\Symbian\Carbide\workspace\QDetroBro\Makefile
	-$(MAKE) -f "c:\Symbian\Carbide\workspace\QDetroBro\Makefile" extension_clean

finalize : c:\Symbian\Carbide\workspace\QDetroBro\Makefile
	-$(MAKE) -f "c:\Symbian\Carbide\workspace\QDetroBro\Makefile" finalize

winscw_deployment_clean : c:\Symbian\Carbide\workspace\QDetroBro\Makefile
	-$(MAKE) -f "c:\Symbian\Carbide\workspace\QDetroBro\Makefile" winscw_deployment_clean

winscw_deployment : c:\Symbian\Carbide\workspace\QDetroBro\Makefile
	-$(MAKE) -f "c:\Symbian\Carbide\workspace\QDetroBro\Makefile" winscw_deployment


