#############################################################################
# Makefile for building: QDetroBro
# Generated by qmake (2.01a) (Qt 4.5.2) on: Mon Sep 7 14:53:24 2009
# Project:  QDetroBro.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile QDetroBro.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/linux-g++-opengl -I. -I/targets/FREMANTLE_X86/usr/include/qt4/QtCore -I/targets/FREMANTLE_X86/usr/include/qt4/QtNetwork -I/targets/FREMANTLE_X86/usr/include/qt4/QtGui -I/targets/FREMANTLE_X86/usr/include/qt4/QtWebKit -I/targets/FREMANTLE_X86/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -Wl,-rpath-link=/usr/lib -lQtWebKit -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = NavigationBarWidget.cpp \
		ChaseWidget.cpp \
		AddressBarWidget.cpp \
		FlickCharm.cpp \
		main.cpp \
		QDetroBro.cpp moc_NavigationBarWidget.cpp \
		moc_ChaseWidget.cpp \
		moc_AddressBarWidget.cpp \
		moc_FlickCharm.cpp \
		moc_QDetroBro.cpp \
		qrc_images.cpp
OBJECTS       = NavigationBarWidget.o \
		ChaseWidget.o \
		AddressBarWidget.o \
		FlickCharm.o \
		main.o \
		QDetroBro.o \
		moc_NavigationBarWidget.o \
		moc_ChaseWidget.o \
		moc_AddressBarWidget.o \
		moc_FlickCharm.o \
		moc_QDetroBro.o \
		qrc_images.o
DIST          = /targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/g++.conf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/release.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QDetroBro.pro
QMAKE_TARGET  = QDetroBro
DESTDIR       = 
TARGET        = QDetroBro

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_NavigationBarWidget.h ui_AddressBarWidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QDetroBro.pro  /targets/FREMANTLE_X86/usr/share/qt4/mkspecs/linux-g++-opengl/qmake.conf /targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/g++.conf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/release.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile QDetroBro.pro
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/g++.conf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/unix.conf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/common/linux.conf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/qconfig.pri:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt_functions.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt_config.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/default_pre.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/release.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/default_post.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/warn_on.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/qt.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/unix/thread.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/moc.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/resources.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/uic.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/yacc.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/lex.prf:
/targets/FREMANTLE_X86/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile QDetroBro.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QDetroBro0.2.2 || $(MKDIR) .tmp/QDetroBro0.2.2 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QDetroBro0.2.2/ && $(COPY_FILE) --parents NavigationBarWidget.h ChaseWidget.h AddressBarWidget.h FlickCharm.h QDetroBro.h .tmp/QDetroBro0.2.2/ && $(COPY_FILE) --parents images.qrc .tmp/QDetroBro0.2.2/ && $(COPY_FILE) --parents NavigationBarWidget.cpp ChaseWidget.cpp AddressBarWidget.cpp FlickCharm.cpp main.cpp QDetroBro.cpp .tmp/QDetroBro0.2.2/ && $(COPY_FILE) --parents NavigationBarWidget.ui AddressBarWidget.ui .tmp/QDetroBro0.2.2/ && (cd `dirname .tmp/QDetroBro0.2.2` && $(TAR) QDetroBro0.2.2.tar QDetroBro0.2.2 && $(COMPRESS) QDetroBro0.2.2.tar) && $(MOVE) `dirname .tmp/QDetroBro0.2.2`/QDetroBro0.2.2.tar.gz . && $(DEL_FILE) -r .tmp/QDetroBro0.2.2


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_NavigationBarWidget.cpp moc_ChaseWidget.cpp moc_AddressBarWidget.cpp moc_FlickCharm.cpp moc_QDetroBro.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_NavigationBarWidget.cpp moc_ChaseWidget.cpp moc_AddressBarWidget.cpp moc_FlickCharm.cpp moc_QDetroBro.cpp
moc_NavigationBarWidget.cpp: ui_NavigationBarWidget.h \
		NavigationBarWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) NavigationBarWidget.h -o moc_NavigationBarWidget.cpp

moc_ChaseWidget.cpp: ChaseWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ChaseWidget.h -o moc_ChaseWidget.cpp

moc_AddressBarWidget.cpp: ui_AddressBarWidget.h \
		ChaseWidget.h \
		AddressBarWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) AddressBarWidget.h -o moc_AddressBarWidget.cpp

moc_FlickCharm.cpp: FlickCharm.h
	/usr/bin/moc $(DEFINES) $(INCPATH) FlickCharm.h -o moc_FlickCharm.cpp

moc_QDetroBro.cpp: AddressBarWidget.h \
		ui_AddressBarWidget.h \
		ChaseWidget.h \
		NavigationBarWidget.h \
		ui_NavigationBarWidget.h \
		QDetroBro.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QDetroBro.h -o moc_QDetroBro.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/slide-horizontal.png \
		images/stop.png \
		images/back.png \
		images/slide-vertical.png \
		images/forward.png \
		images/reload.png \
		images/zoom-in.png \
		images/zoom-out.png \
		images/home.png \
		images/go.png
	/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_NavigationBarWidget.h ui_AddressBarWidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_NavigationBarWidget.h ui_AddressBarWidget.h
ui_NavigationBarWidget.h: NavigationBarWidget.ui
	/usr/bin/uic NavigationBarWidget.ui -o ui_NavigationBarWidget.h

ui_AddressBarWidget.h: AddressBarWidget.ui \
		ChaseWidget.h
	/usr/bin/uic AddressBarWidget.ui -o ui_AddressBarWidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

NavigationBarWidget.o: NavigationBarWidget.cpp NavigationBarWidget.h \
		ui_NavigationBarWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NavigationBarWidget.o NavigationBarWidget.cpp

ChaseWidget.o: ChaseWidget.cpp ChaseWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChaseWidget.o ChaseWidget.cpp

AddressBarWidget.o: AddressBarWidget.cpp AddressBarWidget.h \
		ui_AddressBarWidget.h \
		ChaseWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddressBarWidget.o AddressBarWidget.cpp

FlickCharm.o: FlickCharm.cpp FlickCharm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FlickCharm.o FlickCharm.cpp

main.o: main.cpp QDetroBro.h \
		AddressBarWidget.h \
		ui_AddressBarWidget.h \
		ChaseWidget.h \
		NavigationBarWidget.h \
		ui_NavigationBarWidget.h \
		sym_iap_util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

QDetroBro.o: QDetroBro.cpp QDetroBro.h \
		AddressBarWidget.h \
		ui_AddressBarWidget.h \
		ChaseWidget.h \
		NavigationBarWidget.h \
		ui_NavigationBarWidget.h \
		FlickCharm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QDetroBro.o QDetroBro.cpp

moc_NavigationBarWidget.o: moc_NavigationBarWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NavigationBarWidget.o moc_NavigationBarWidget.cpp

moc_ChaseWidget.o: moc_ChaseWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ChaseWidget.o moc_ChaseWidget.cpp

moc_AddressBarWidget.o: moc_AddressBarWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddressBarWidget.o moc_AddressBarWidget.cpp

moc_FlickCharm.o: moc_FlickCharm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FlickCharm.o moc_FlickCharm.cpp

moc_QDetroBro.o: moc_QDetroBro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QDetroBro.o moc_QDetroBro.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

